### ISSUE TITLE
How to run as a service

### ISSUE THREAD

**Issue by hi-flyer** [zwave-js/zwavejs2mqtt#1622]
I used to run zwave2mqtt as a service. which worked great until today. The service does not start now. I can start as the user from a terminal. So as I could not figure out and you suggested to move to Js version, I have but I still get the same error when trying to set up as a service. The command run as user 
docker run --rm -it -p 8091:8091 -p 3000:3000 --device=/dev/ttyACM0 -v $(pwd)/store:/usr/src/app/store zwavejs/zwavejs2mqtt:latest
runs picking up the existing setups

I am on Ubuntu 20.04 and to run as a service I ran following with results as shown
wget https://raw.githubusercontent.com/zwave-js/zwavejs2mqtt/master/docker/docker-compose.yml
downloads the file docker-compose.yaml which says
version: '3.7'
services:
  zwavejs2mqtt:
    container_name: zwavejs2mqtt
    image: zwavejs/zwavejs2mqtt:latest
    restart: always
    tty: true
    stop_signal: SIGINT
    environment:
      - SESSION_SECRET=mysupersecretkey
    # - TZ=America/Los_Angeles  # uncomment and edit to match you timezone if you want logs time and dates to match your timezone instead of UTC.
    networks:
      - zwave
    devices:
      - '/dev/ttyACM0:/dev/ttyACM0'
    volumes:
      - ./store:/usr/src/app/store
    ports:
      - '8091:8091' # port for web interface
      - '3000:3000' # port for zwave-js websocket server
networks:
  zwave:
volumes:
  zwave-config:
    name: zwave-config
but docker-compose up says
cannot update snap namespace: cannot create symlink in "/etc/docker": existing file in the way
snap-update-ns failed with code 1

I have tried docker-compose up and sudo docker-compose up but get the same answer.
do you have a suggestion what is wrong and how to fix.
thanks

**Comment by robertsLando** [comment]
Humm  sincerly I have no idea why you are getting a snap error while running a docker compose command, @jmgiaever anything that could be related to your snap package?

**Comment by jmgiaever** [comment]
Hi, no it's not. I guess @hi-flyer is using the snap package of Docker. Check with `snap list | grep docker` if it's installed with snapd.

BUT it looks like docker have been (or still is) installed in a different way (e.g through apt) which makes a conflict, and the symlink to `/etc/docker` is not allowed since it will modify the behavior of docker on the host-system.

I think @hi-flyer need to remove the other docker-package and then make sure that the `/etc/docker` directory is deleted, to fix this issue. This should be done with caution to not mess up other containers that might be running!

If @hi-flyer is using a debian based host OS, he can check with `dpkg --get-selections | grep docker` and remove it with `sudo apt purge --remove docker`.

**Comment by hi-flyer** [comment]
Thank you both for your suggestions. I appreciate all help.
So, the system did its automatic reboot last night and everything seems to have started back up and is working. (I really hate things that suddenly fix themselves for no reason as they tend to show back up later). Oh well.
I will convert to zwavejs2mqtt today and how all goes well.
I will get back to you if I seem successful.

**Comment by hi-flyer** [comment]
I have converted successfully. I did not have to remove any docker programs as suggested. It did take some effort to remove the zwave2mqtt but finally accomplished. then the zwavejs2mqtt worked.
completed my changes to NYMEA to accommodate changes in protocol. It was painful but done.
Thanks again to both of you. Have a good day.
