### ISSUE TITLE
[feat]

### ISSUE THREAD

**Issue by stu247** [zwave-js/zwavejs2mqtt#1935]
**Is your feature request related to a problem? Please describe.**
The description on how to set up docker container at (https://zwave-js.github.io/zwavejs2mqtt/#/getting-started/docker) allows anyone in the network to control Z-Wave WS Server.

**Describe the solution you'd like**
If the service connecting to Z-Wave WS Server is on the same host as the Z-Wave to MQTT container, then the docker command to run the Z-Wave to MQTT container can stipulate to only allow connections coming from the localhost.  This is a lot safer then allowing connections from anywhere on the network.  This is done by changing:

-p 3000:3000

to

-p 127.0.0.1:3000:3000

Please consider adding that information to documentation at the URL above.

**Describe alternatives you've considered**
Another option would be using iptables on the host, but the option above is much simpler.

**Additional context**
NA.

**Comment by blhoward2** [comment]
Eh, there are lots of different ways to secure containers and we generally don't weigh into that. The UI isn't even password protected by default so I'm not sure what the WS really exposes beyond that. I'm also not sure that we can assume its coming from localhost, as many people address the container using their device IP from within the integration and what this is really doing is binding to 127.0.1.1 instead of 0.0.0.0.

I'll meet you partway. I added a note to the bottom.

**Comment by stu247** [comment]
Sounds great.  Thanks.
