### ISSUE TITLE
[Bug]: 6.4.1 showing as latest version when using snap package

### ISSUE THREAD

**Issue by junior466** [zwave-js/zwavejs2mqtt#2300]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Snap

### Zwavejs2Mqtt version

6.4.1

### ZwaveJS version

8.11.1

### Describe the bug

UI shows that 6.4.1 is the latest version. Checking for update through the UI doesn't show 6.5.2 no matter how many times I try. 

### To Reproduce

Check for update.

### Expected behavior

Latest version shown with option to update.

**Comment by kpine** [comment]
The `latest/candidate` channel of the snap package has 6.5.2. Based on the description of the channels, as a Home Assistant user you probably want to switch to that channel. The stable channel will potentially always be out of date since zwavejs2mqtt minor releases can contain updates to the websocket server.
