### ISSUE TITLE
Entire zwave network went dead overnight & continuous dead node issues in 2022

### ISSUE THREAD

**Issue by cappiel** [zwave-js/zwavejs2mqtt#2318]
I've been having dead node issues over the past 2 months, so spent an hour or so yesterday and re-flashed my zoom Gen5 ZW090 and started from scratch. 15 nodes were active all day yesterday. Then today, all dead....

The stick is about 20 feet from the first switch in the wall. I really don't think it's a location issue, it's been fine for 3+ years. I'm out of ideas at this point. 

Is there anything in the logs that sticks out? Just seems like my nodes stop ack randomly. 

zwavejs log - [https://pastebin.pl/view/ba03a94f](https://pastebin.pl/view/ba03a94f)

zwavejs2mqtt - [https://pastebin.pl/view/06e64918](https://pastebin.pl/view/06e64918)

nodes - [https://pastebin.pl/view/dbf8d0b4](https://pastebin.pl/view/dbf8d0b4)

**Comment by cappiel** [comment]
zwavejs2mqtt: 6.5.2
zwave-js: 8.11.6
home id: 3224592993
home hex: 0xc0336261

Versions also

**Comment by robertsLando** [comment]
Your links don't work

**Comment by cappiel** [comment]
> Your links don't work

Fixed, github novice...

**Comment by robertsLando** [comment]
@AlCalzone I don't see any error on my side

**Comment by AlCalzone** [comment]
Hard to say what's going on here. Most communication attempts fail because there is no acknowledgement from the nodes, like this:
```
transmit status:        NoAck, took 5550 ms
routing attempts:       25
```
There is the odd success here and there, but even some of those take >10 attempts.

Your controller doesn't tell the driver which nodes it attempts to route through, this seems to be a 700 series feature. But it could be that most routes go through a single node and that this node failed. Have you tried healing the network yet? Or individual nodes? Maybe the route check tools in the zwavejs2mqtt network map can help narrow down the culprit.

**Comment by cappiel** [comment]
Thank you both! This morning they are all back to green/active now. did a heal network this morning and now everything is going through 1 central switch now except the lock. so lets see how that goes. 

I'll report back, thank you again for looking

**Comment by cappiel** [comment]
Grabbed a plug and it seems to be meshing much better, thank you both
