### ISSUE TITLE
Icons Dissapeared

### ISSUE THREAD

**Issue by junior466** [zwave-js/zwavejs2mqtt#2574]
My icons suddenly disappeared:

![Screen Shot 2022-08-06 at 12 08 50 PM](https://user-images.githubusercontent.com/22748735/183256978-0fbee6b9-b2a9-49af-b5d7-097828425754.png)

Running snap version on Ubuntu.

**Comment by robertsLando** [comment]
Fixed in 6.15.1 version

**Comment by robertsLando** [comment]
cc @jmgiaever

**Comment by jmgiaever** [comment]
I'm aware, but I haven't been able to update because of my holiday. 

However this version is only in the edge channel, which shouldn't be used for a daily setup. 

It might periodically frequently **(auto)** update, even with packages that is purely intended for testing. E.g to test a zwjs or z2m branch with features and fixes. 

Everyone should use the candidate or stable channels. :)
