### ISSUE TITLE
[feat] Allow "targetXXXXX" topics to be directly used, without /set

### ISSUE THREAD

**Issue by DanielWinks** [zwave-js/zwavejs2mqtt#386]
**Is your feature request related to a problem? Please describe.**

With the changes to the topics, compared to zwave2mqtt, it doesn't make sense to have `/set` still used.

In Z2M there was just 1 topic, for both "currentValue" and "targetValue", so in order to set a value, you used a subtopic of `/set`. In Zjs2MQTT, we have one topic for "currentValue" and another that is only used for setting values, "targetValue".

**Describe the solution you'd like**

Either remove `\set` entirely, or at least allow for directly sending value update to the "targetValue" topic. I was surprised to find out I even needed `/set` on this, as it doesn't feel intuitive now that there's separate topics for each. 

**Describe alternatives you've considered**
None, simple feature request to avoid a bit of "why am I using a subtopic for setting values on a topic that exists solely for setting values?"

**Additional context**
None.

**Comment by robertsLando** [comment]
@DanielWinks this cannot be done. The reason is simple, the get topic is also used to get a feedback about the value you wrote, in some cases this could cause infinite loops (you send a message, the feedback comes and triggers a new write and repeats). This could be prevented someway by adding some kind of id in payload to identify those loops but will also make the entire mqtt structure inconsistent. Not worth the benefits

**Comment by DanielWinks** [comment]
Ah, I figured with the new "currentValue" and "targetValue" that targetValue itself would prevent such a loop, but you know the code and I don't. Anyway, thanks so much for all you do for this project, it's truly appreciated.
