### ISSUE TITLE
Dashboard stuck on loading screen 1.2.0

### ISSUE THREAD

**Issue by drjjr2** [zwave-js/zwavejs2mqtt#622]
Just updated to 1.2.0 and now my dashboard is stuck on "Loading." The container logs show that it is running. I just can't access the dashboad.
Any suggestions would be welcome.

**Comment by hareve** [comment]
I also get this. In dev-tools I see this error: Could not load content for webpack://zwavejs2mqtt/static/js/app.d0932a2a2f1c71b1d987.js (HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME)

**Comment by decairn** [comment]
Chrome F12 adds further context to that error before the dev-tools error: Uncaught (in promise) Error: Redirected when going from "/" to "/settings" via a navigation guard

**Comment by Swiftnesses** [comment]
I know it adds little value, but I have the same issue.

**Comment by drjjr2** [comment]
This looks like it was fixed with 1.2.1

**Comment by robertsLando** [comment]
Fix on 1.2.1

**Comment by Swiftnesses** [comment]
Thank you @robertsLando - super fast as always!

**Comment by robertsLando** [comment]
Sorry for the inconvenience 🙏🏻 

Unfortunately as I said in slack channel this bug was not happening on my tests as it was depending on the missing auth property in settings (undefined). I check it to be true or false, this is the purpose of the spinner, it waits to check the auth to show you the login or directly login you but was returning undefined
