### ISSUE TITLE
[question] Setting Up ZWAVE network with 15 components - I‘m in trouble

### ISSUE THREAD

**Issue by OlliF69** [zwave-js/zwavejs2mqtt#660]
Hi,
since a few days I try to set up my zwave network. But I don‘t understand, how...
First - firts I drove with ZWAVE QS - now I try to switch to zwave JS. 
I installed the zwave JS addon - it works, most of my nodes were found.
As I understood now I need a MQTT broker for cummunications with home assistant. Therefore I installed zwavejs2mqtt add-on. And here is my problem:
I started the addon and in the LOG file I got the message: path not found.
Ok this is in my eyes clear, because I don‘t insert any information about my USB zwave stick. I thought if I enabled the option DISABLE MQTT Gateway (use zwavejs2mgtt only as control panel) it will works... But I still can‘t control my zwave components.
What did I understood wrong?
If I put the information in the add-on it found my components, but my home assistant will restart every 5 minutes. Zwavejs2mqtt and zwave-js are running parallel, an d I thought this should be not.I think I don‘t understand the work of both addons right. 
Perhaps someone cann tell me, how should I use both of them...
Thanks

**Comment by ivdimitro** [comment]
Hi, The home assistant zwave JS integration and zwavejs2mqtt bring their own separate zwave JS servers. I guess that's why you are having problems. 
The zwave GUI in HA quite limited but if it is sufficient for your needs you do not need to do anything else. 
If need finer grain control of your devices ot better visualization of your network, I would recommend to install zwavejs2mqtt and pass the usb stick to it. In the zjs2mqtt you can control if you want the node information to be exported via MQTT or via the zwaveJS server. Those options only define how HA will interface with zwave driver. The device level controls can be done via zwavejs2mqtt gui irrespective of the HA integration. 
If you do not have MQTT broker use the JS server and pass the correct IP to the integration.
Do not enable MQTT and the zwave LS server simultaneously as your device might get scrambled.
