### ISSUE TITLE
[question] Debug tab doesn't show any info?

### ISSUE THREAD

**Issue by Lopton** [zwave-js/zwavejs2mqtt#716]
Is anyone else not seeing any data in the new debug tab? I click start, but no messages ever appear in the debug tab now that it has been moved to the left bar and given its own page. 

I was used to using this to monitor z-wave traffic in past versions, helpful troubleshooting tool.

**Comment by robertsLando** [comment]
![Schermata da 2021-02-24 08-55-42](https://user-images.githubusercontent.com/11502495/108966152-2134d700-767e-11eb-8d5a-e970d5c882ad.png)

It is woorking on my side, it could be that there are no messsages coming?

**Comment by towerhand** [comment]
Since I ran into the same issue in the past thinking the debug window wasn't working when in fact it was, I would like to take this opportunity to request some short of feedback from the system when we press the start and stop button, maybe just a message saying "debug starting now...." when pressing start and "debugging ended" when pressing stop or something like that.

**Comment by Lopton** [comment]
Hmm, there are messages I should be seeing, if I go look in the new store file viewer I can see the messages logged there. But nothing ever shows in the debug tab for me. I've tried chrome and firefox. I've upgraded to the latest version also. Since it's just me I'll close the issue and look more at my end.

**Comment by robertsLando** [comment]
@Lopton Do you see any error in console? Also you colud try to open dev tools and go to Network tab to see the incoming packets from WS

**Comment by Lopton** [comment]
@robertsLando No errors in the console, no traffic in the network, it's as if nothing happens when I click the start button. I cleared the cache and force reloaded the page, nothing.  I'll dive into the JS further later. So weird.
