### ISSUE TITLE
[feat] Ability to manage better State Sensitive Command Classes

### ISSUE THREAD

**Issue by billiaz** [zwave-js/zwavejs2mqtt#77]
## Issue

We currently face an issue, which the previous driver solved with it's own internal process.

The new driver (zwave-js) does manage all the value updates from different command classes. There are specific classes which might enter a state, but have no signal of exiting this state. This is by design of Z-wave and unfortunately we cannot avoid it. The reason usually is for saving energy.

An example is the Central Scene, which delivers information about button press (short), button hold down and button release (and only release in case was hold down).
In this situation, once we press the button for a short time, we do not receive an update for it's release.

Pressing the button, and triggering short press, this happens:
1. Cache keeps the last state as button pressed
2. If already been pressed before, new state is from 
```z2m:Zwave Node 87: value updated: 91-0-scene-004 0 => 0```
3. There is no inactive state.

Previous driver was behaving like this:
```
2020-12-13T12:47:35.599Z z2m:Zwave zwave node 87: changed: 91-1-3:Scene 3:Inactive -> Pressed 1 Time
2020-12-13T12:47:36.599Z z2m:Zwave zwave node 87: changed: 91-1-3:Scene 3:Pressed 1 Time -> Inactive
```

The current way, causes issues on automations, as we can by a restart trigger a button press (from cache)

## Proposal for more solving this

I suggest to add a category of command classes called `State Sensitive Command Class`. This will have some different characteristics compared to remaining classes

### Proposed characteristics to support
- On startup or restart: do not update the value from cache, and set the proprty with undefined value
- Ability On Value update, after specific time (which can be configurable) to revert to undefined value (global SSCC setting)
- Ability to enable/disable the Retention of topics of SSCC 
- Add value on payload for better understanding where the value comes from (from cache or not)

**Comment by AlCalzone** [comment]
I still have some questions which haven't been answered yet:
**Why** do we need to emit an update for the values which are read from cache on startup/restart? What happens if we don't?
Or is that due to MQTT retention (which seems to be on for all values)?

---

**If** it is due to the latter, handling this shouldn't happen on a per-CC basis but rather on a per-value basis (e.g. by adding a new metadata property). In this case I propose:
* the `kind` of a value can be `"state"` or `"event"`
* all values should be assumed to be states, unless metadata says otherwise
* metadata can be used to set the `kind` of a value

zwave-js would expose this info via the usual channels.

zwavejs2mqtt could then:
* disable retention for `kind: "event"` value IDs
* Not publish `kind: "event"` value IDs on startup
* And if absolutely required: reset/expire the value for `kind: "event"` value IDs after a while (I don't think it is with the state/event separation)

**Comment by robertsLando** [comment]
> Why do we need to emit an update for the values which are read from cache on startup/restart?

We could skip publish when value is coming from cache, usually this is done because for some reason user could have cleaned all the retained values on broker and this would init them. 

Then to fix the retain problem of such values we should firstly identify them and then set the retain flag to false when publishing them. 

FYI @AlCalzone retain flag is a flag set when publishing a message to mqtt, when retain is true that message is stored on broker side (just the last one not all), when a client subscribes to a topic it will receive all retained messages matching that topic, it's used to get latest message sent to a specific topic

**Comment by AlCalzone** [comment]
Ok so in other words:
> Why do we need to emit an update for the values which are read from cache on startup/restart? What happens if we don't?

If we don't, the broker might not have all values, since they might have been cleared. Is it possible to feed the values to the broker **without** causing it to emit an event for that? Or does that have other downsides?

> Then to fix the retain problem of such values we should firstly identify them and then set the retain flag to false when publishing them.

So okay to what I wrote above?

**Comment by robertsLando** [comment]
> Is it possible to feed the values to the broker without causing it to emit an event for that

Nope, this cannot be done.

> So +1 to what I wrote above?

Absolutely! In poor words the only problem remains how to handle values coming from cache on startup. IMO for this the only way would be adding a flag into the payload `"fromCache": true`.
